import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import React from 'react'
import Slider from '@/components/Slider/Slider';
import { use, useState } from 'react';
import SubNav from '@/components/SubNav/SubNav';

function index() {
    return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
          <div className='container'>
           <SubNav />
          </div>
           <Slider />
            <div className='challengeContent'>
             <div className='row d-flex justify-content-center'>
              <div className='col-sm-4'>
                <div className='logoChallenge'>
                  <img src="logo9.png" />
                  <span>Chicago<br />Bulls</span>
                </div>
              </div>
                <div className='col-sm-2 align-self-center'>
                  <p>vs</p>
                </div>
              <div className='col-sm-4'>
                <div className='logoChallenge'>
                <img src="logo10.png" />
                <span>Toronto<br />Raptors</span>
                </div>
              </div>
             </div>
            </div>
          </main>
          <style jsx>{`
            .challengeContent{
              max-width:1130px;
              margin:0 auto;
              margin-top:100px;
            }
            .challengeContent p{
              text-align: center;
              font-size: 60px;
              font-weight: 700;
              font-family: system-ui;
            }
            .logoChallenge span{
              display: block;
              margin: 15px auto;
              text-align: center;
              font-weight: 700;
              font-size: 30px;
            }
            .logoChallenge img{
              width: 70%;
              margin: 0 auto;
              display: block;

            }
            `}</style>
        </>
      )
}

export default index;