import React , {useEffect, useState} from 'react';
import Head from 'next/head';
import Divider from '@/components/Divider/Divider';
import SubNav from '@/components/SubNav/SubNav';
import Calendar from 'react-calendar';
import { FaCalendarAlt } from "react-icons/fa";
import 'react-calendar/dist/Calendar.css';
import Live from '@/components/Live/Live';


function scores() {

    const [date , setDate]= useState(new Date())
    const [show , setShow]= useState(false)

    const onChange = data => {
        setDate(data)
    }
    const showDate = () => {
        setShow(true)
    }
    useEffect(() => {
        window.addEventListener('dblclick', () => {
            setShow(false)
        })
    })
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
    <div className='container'>
        <SubNav />
        <Divider title={"NBA SCORES"}/>
        <div className='Date'>
            <p>{date.toDateString()}
            <span onClick={showDate}><FaCalendarAlt /></span>
            </p>
            <div className='Calendar'>
            {show ? (
                    <Calendar onChange={onChange} value={date}/>
            ) : null}
            </div>
        </div>
         <div className='row'>
           <div className='col-sm-12 col-md-6 col-lg-4'>
             <div className='ScoresCard'>
                <p>
                    Pacers
                    <img  src="./logo3.png" />
                </p>
                <p>
                    Celtices
                    <img  src="./logo1.png" />
                </p>
                <a>1:00a</a>
                <a>Struggling Rockets stand in the way of Grizzlies and their 5th straight win</a>
                <Live />
             </div>
           </div>
        {true && (
            <div className='col-sm-12 col-md-6 col-lg-4'>
               <div className='ScoresCard done'>
                  <p>
                      Pacers
                      <img  src="./logo4.png" />
                      <span>15</span>
                  </p>
                  <p>
                      Celtices
                      <img  src="./logo2.png" />
                      <span>6</span>
                  </p>
                  <a className={true ? "black" : ""}>{true ? "Final" : "1:00am"}</a>
                  <a className={true ? "black" : ""}>Struggling Rockets stand in the way of Grizzlies and their 5th straight win</a>
               </div>
             </div>
        )}
           <div className='col-sm-12 col-md-6 col-lg-4'>
             <div className='ScoresCard'>
                <p>
                    Pacers
                    <img  src="./logo5.png" />
                </p>
                <p>
                    Celtices
                    <img  src="./logo6.png" />
                </p>
                <a>1:00a</a>
                <a>Struggling Rockets stand in the way of Grizzlies and their 5th straight win</a>
             </div>
           </div>
           <div className='col-sm-12 col-md-6 col-lg-4'>
             <div className='ScoresCard'>
                <p>
                    Pacers
                    <img  src="./logo7.png" />
                </p>
                <p>
                    Celtices
                    <img  src="./logo8.png" />
                </p>
                <a>1:00a</a>
                <a>Struggling Rockets stand in the way of Grizzlies and their 5th straight win</a>
             </div>
           </div>
           <div className='col-sm-12 col-md-6 col-lg-4'>
             <div className='ScoresCard'>
                <p>
                    Pacers
                    <img  src="./logo3.png" />
                </p>
                <p>
                    Celtices
                    <img  src="./logo1.png" />
                </p>
                <a>1:00a</a>
                <a>Struggling Rockets stand in the way of Grizzlies and their 5th straight win</a>
             </div>
           </div>
           <div className='col-sm-12 col-md-6 col-lg-4'>
             <div className='ScoresCard'>
                <p>
                    Pacers
                    <img  src="./logo3.png" />
                </p>
                <p>
                    Celtices
                    <img  src="./logo1.png" />
                </p>
                <a>1:00a</a>
                <a>Struggling Rockets stand in the way of Grizzlies and their 5th straight win</a>
             </div>
           </div>
        </div>
    </div>
    </main>
    <style jsx>{`
    .Date .Calendar{
        display: inline-block;
        width: 277px;
        margin-left: 50px;
        position: absolute;
        z-index: 999;

    }
    .Date p {
        display:inline-block;
        position:relative;
        padding: 10px 40px 10px 5px;
        font-size: 19px;
        font-weight: 700;
    }
    .Date span{
        position: absolute;
        right: 0;
        top: 3px;
        font-size: 25px;
    }
    .ScoresCard{
        padding: 20px 11px;
        border: 1px solid #ccc;
        margin-bottom:20px;
        position: relative;
        border-radius: 2%;
    }
    .done{
        background-color: #ccc;
        color: #000;
        font-weight:bold
    }
    .black{
        color:#000 !important;
    }
     .ScoresCard  p{
        position: relative;
        padding: 10px 32px 8px 68px;
        font-size: 23px;
        margin-bottom: 10px;
    }
    .ScoresCard p img{
        position: absolute;
        left: 0;
        top: 7px;
        width: 45px;
        height: 45px;
    }
    .ScoresCard p span{
        font-weight: 700;
        font-size: 30px;
        position: absolute;
        right: 13px;
    
    }
    .ScoresCard a{
        display: block;
        text-align: center;
        cursor: pointer;
    }
    .ScoresCard a:hover{
        color:#fff
    }
    .ScoresCard a:last-of-type{
        text-align: left;
        margin: 19px 0 0;
    }
       }
      `}</style>
    </>

  )
}

export default scores