import React , {useEffect, useState} from 'react';
import Head from 'next/head';
import Divider from '@/components/Divider/Divider';
import SubNav from '@/components/SubNav/SubNav';

function standings() {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
    <div className='container'>
        <SubNav />
        <Divider title={"NHL STANDINGS"}/>

        <table className="table">
<thead>
  <tr>
    <th colSpan={8}>East Atlantic</th>
    <th scope="col">W</th>
    <th scope="col">L</th>
    <th scope="col">Otl</th>
    <th scope="col">pts</th>
    <th scope="col">Gf</th>
    <th scope="col">Ga</th>
  </tr>
</thead>
<tbody>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo1.png" width={45} height={45}/>
        latin periz
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo2.png" width={45} height={45}/>
        atalntic
    </a>
  </td>
  <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo4.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo5.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo6.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
</tbody>
</table> 

<table className="table">
<thead>
  <tr>
    <th colSpan={8}>East Atlantic</th>
    <th scope="col">W</th>
    <th scope="col">L</th>
    <th scope="col">Otl</th>
    <th scope="col">pts</th>
    <th scope="col">Gf</th>
    <th scope="col">Ga</th>
  </tr>
</thead>
<tbody>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo1.png" width={45} height={45}/>
        latin periz
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo2.png" width={45} height={45}/>
        atalntic
    </a>
  </td>
  <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo4.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo5.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo6.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
</tbody>
</table> 

<table className="table">
<thead>
  <tr>
    <th colSpan={8}>East Atlantic</th>
    <th scope="col">W</th>
    <th scope="col">L</th>
    <th scope="col">Otl</th>
    <th scope="col">pts</th>
    <th scope="col">Gf</th>
    <th scope="col">Ga</th>
  </tr>
</thead>
<tbody>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo1.png" width={45} height={45}/>
        latin periz
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo2.png" width={45} height={45}/>
        atalntic
    </a>
  </td>
  <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo4.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo5.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo6.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
</tbody>
</table> 

<table className="table">
<thead>
  <tr>
    <th colSpan={8}>East Atlantic</th>
    <th scope="col">W</th>
    <th scope="col">L</th>
    <th scope="col">Otl</th>
    <th scope="col">pts</th>
    <th scope="col">Gf</th>
    <th scope="col">Ga</th>
  </tr>
</thead>
<tbody>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo1.png" width={45} height={45}/>
        latin periz
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo2.png" width={45} height={45}/>
        atalntic
    </a>
  </td>
  <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo4.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo5.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
  <tr>
  <td colSpan={8}>
    <a href="/">
        <img src="logo6.png" width={45} height={45}/>
        Maple Leafs
    </a>
  </td>
    <td>48</td>
    <td>75</td>
    <td>63</td>
    <td>15</td>
    <td>30</td>
    <td>17</td>
  </tr>
</tbody>
</table> 
        
     </div>
     </main>
     <style jsx>{`
     table{
        margin-bottom:30px
     }
        td,th{
            padding-left:0;
        }
        td img{
            margin-right:10px;
            top: -1px;
            position: relative;
            width:32px;
            height:32px;
        }
        table a:hover{
            color:red !important;
        }
      `}</style>
    </>
  )
}

export default standings 
